[dependencies]
fastly = "^0.11.0"
ipnetwork = "0.20.0"

[package]
authors = []
edition = "2021"
license = "MIT"
name = "fastly-compute-edge-demo"
publish = false
version = "0.1.0"

[profile]
  [profile.release]
    debug = 1
