# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["rui@chenrui.dev"]
description = "fastly-compute-edge-demo, https://github.com/chenrui333/fastly-compute-edge-demo"
language = "rust"
manifest_version = 2
name = "fastly-compute-edge-demo"
service_id = "3P8d99kmQc6GK2lpLPvtmk"

[local_server]
  [local_server.backends]
    [local_server.backends.httpbin]
      url = "https://httpbin.org"
