name: hurl

on:
  push:
    branches:
      - main
    paths:
      - hurl/**
      - .github/workflows/hurl.yml
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1-5"

jobs:
  hurl:
    name: hurl
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Install hurl
        run: |
          cd /usr/local/bin && curl -fsSL https://github.com/Orange-OpenSource/hurl/releases/download/$HURL_VERSION/hurl-$HURL_VERSION-x86_64-linux.tar.gz | sudo tar xz --strip-components 1
          hurl --version
        env:
          HURL_VERSION: 3.0.0

      - name: Run tests
        run: hurl --retry --retry-max-count 5 --test --glob "hurl/**/*.hurl"
