name: main

on:
  push:
  pull_request:

env:
  # for fastly cli
  FASTLY_API_TOKEN:      ${{ secrets.FASTLY_API_TOKEN }}
  # for terraform provider
  FASTLY_API_KEY:        ${{ secrets.FASTLY_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.54.0 # current Rust toolchain for Compute@Edge
            target: wasm32-wasi # WebAssembly target

      - name: Set up Fastly CLI
        uses: fastly/compute-actions/setup@b9d14a5b0371ab6c2640a59f05353b2bda4eed74

      - name: build and deploy
        if: github.ref == 'refs/heads/main'
        run: |
          fastly compute build
          fastly compute deploy
