name: main

on:
  push:
  pull_request:

env:
  # for fastly cli
  FASTLY_API_TOKEN:      ${{ secrets.FASTLY_API_TOKEN }}
  # for terraform provider
  FASTLY_API_KEY:        ${{ secrets.FASTLY_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.54.0 # current Rust toolchain for Compute@Edge
            target: wasm32-wasi # WebAssembly target

      - name: Set up Fastly CLI
        uses: fastly/compute-actions/setup@da4f7b0e63d8963d5de811a8ec799f265b3a25aa

      - name: build and deploy
        if: github.ref == 'refs/heads/main'
        run: |
          fastly compute build
          fastly compute deploy

      - uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.1.7

      - name: Wait for Previous Deployment
        uses: softprops/turnstyle@master
        timeout-minutes: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # checks the workflows runs across branches
          same-branch-only: false

      - name: Run terraform init
        run: |
          terraform init -input=false -no-color
      - name: Run terraform plan
        run: |
          terraform plan -input=false -refresh -no-color
      - name: Run terraform apply
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply -no-color -auto-approve
      - name: commit the diff
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          changed=$(git diff --name-only --diff-filter=ACMRT .)
          if [[ -n "$changed" ]]; then
            echo "Persist tfstate change"
            git diff
            git add .
            git commit -m 'BOT: persist tfstate change'
            git push origin main
          fi
