name: main

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'hurl/**'
      - '.github/workflows/main.yml'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'hurl/**'
      - '.github/workflows/main.yml'
    branches:
      - main

env:
  # for fastly cli
  FASTLY_API_TOKEN:      ${{ secrets.FASTLY_API_KEY }}
  # for terraform provider
  FASTLY_API_KEY:        ${{ secrets.FASTLY_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Wait for Previous Deployment
        uses: softprops/turnstyle@master
        timeout-minutes: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # checks the workflows runs across branches
          same-branch-only: false

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: wasm32-wasi # WebAssembly target

      - name: Set up Fastly CLI
        uses: fastly/compute-actions/setup@d811a690308a79ebdcadf968999f2b194c1858f6

      - name: build
        if: github.event_name == 'pull_request'
        run: fastly compute build

      - name: publish (build and deploy)
        if: github.ref == 'refs/heads/main'
        run: |
          fastly compute publish
